name: alarm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.4
  battery: ^2.0.3
  # audioplayers: ^0.19.1
  assets_audio_player: ^3.0.3+6
  get_storage:
  percent_indicator: ^3.0.1
  native_admob_flutter: ^1.5.0
  flutter: 
    sdk: flutter
  google_mobile_ads: ^0.13.3
  flutter_launcher_icons: ^0.9.1

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo-alarm-battery.png"


flutter: 
  uses-material-design: true

  assets:
    - assets/